spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: update

