server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:${MYSQL_PORT}/question?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}
    consumer:
      auto-offset-reset: latest
      group-id: question
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
config:
  client:
    origin: ${DOMAIN_IP}
  jwt:
    secret: ${JWT_SECRET}