spring:
  datasource:
    url: jdbc:mysql://10.128.0.12:3306/question?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ity
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: 10.128.0.12:9092
    consumer:
      auto-offset-reset: latest
      group-id: question
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8082
