### getAllArticle (질문 조회)
GET http://localhost:8082/api/v1/question/article
Accept: application/json


### insertArticle(질문 작성)
POST http://localhost:8082/api/v1/question/article
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuyCrOyekCIsImlkIjoiMTI1MGI2M2QtN2RlMi00MzllLWEzMTktZDY4NDBiMjhjY2Y4IiwicHJvZmlsZUltYWdlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8wOS8yMS8xOC8xNy9hdXRvbW9iaWxlLTgyNjczNjlfMTI4MC5qcGciLCJlbWFpbCI6IjI3IiwiZXhwIjoxNjk5NDMzMzE2fQ.Z_HZa5MiBx8AkG16AgqH42Q9nE1LKVQMDYEy6wkWqZA
Content-Type: application/json

{
  "category": "STRESS",
  "difficulty": "어려움",
  "title" : "새로운글",
  "content": "새로운글"

}

### deleteArticle(질문 삭제)
DELETE http://localhost:8082/api/v1/question/article/26
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuyCrOyekCIsImlkIjoiMWJlYTJhMzYtN2U4Yi00ZDM1LThjMzQtMGQwNGNkODUwZTExIiwicHJvZmlsZUltYWdlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8wOS8yMS8xOC8xNy9hdXRvbW9iaWxlLTgyNjczNjlfMTI4MC5qcGciLCJlbWFpbCI6IjI1IiwiZXhwIjoxNjk5NDMwNTM5fQ.avaT-kFDV97a-6thaSC31YBHDiuZGRYRpKhlZ_tXXd8

### findArticleById(질문 상세조회)
GET http://localhost:8082/api/v1/question/article/27
Accept: application/json

### updateArticle(질문 업데이트)
PUT http://localhost:8082/api/v1/question/article/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuwlOq_iCIsImlkIjoiYjJmYTBkZmItZDE5My00YjAyLTk0MDYtMzYzMDYwOWNkM2U4IiwicHJvZmlsZUltYWdlVXJsIjoi67CU6r-IIiwiZW1haWwiOiIyMSIsImV4cCI6MTY5OTI2MzMyOX0.br3fzParrtZXh669Ct4dMjZhs2tdnuwPHdskaNH4VMM
Content-Type: application/json

{
  "category": "ART",
  "difficulty": "d",
  "title" : "d",
  "content": "d"

}

### insertComment(댓글 등록)
POST http://localhost:8082/api/v1/question/comment/26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuyCrOyekCIsImlkIjoiMWJlYTJhMzYtN2U4Yi00ZDM1LThjMzQtMGQwNGNkODUwZTExIiwicHJvZmlsZUltYWdlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8wOS8yMS8xOC8xNy9hdXRvbW9iaWxlLTgyNjczNjlfMTI4MC5qcGciLCJlbWFpbCI6IjI1IiwiZXhwIjoxNjk5NDMwNTM5fQ.avaT-kFDV97a-6thaSC31YBHDiuZGRYRpKhlZ_tXXd8


{
  "content" : "수정입니다."
}

### deleteComment(댓글 삭제)
DELETE http://localhost:8082/api/v1/question/comment/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuuwlOq_iCIsImlkIjoiYjJmYTBkZmItZDE5My00YjAyLTk0MDYtMzYzMDYwOWNkM2U4IiwicHJvZmlsZUltYWdlVXJsIjoi67CU6r-IIiwiZW1haWwiOiIyMSIsImV4cCI6MTY5OTI3Mjc3Nn0.pDfVzmvWhsIucUj3xFQyc5fmWcwhNuclvmMmU5cBEC4
