### getAllArticle (질문 조회)
GET http://localhost:8082/api/v1/question/article
Accept: application/json


### insertArticle(질문 작성)
POST http://localhost:8082/api/v1/question/article
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6Ik5pY2tuYW1lMTIzNCIsImlkIjoiOThlY2ZlYzAtOWM2OS00NjEwLWE2M2YtODAwYzY4MDEwYjdkIiwicHJvZmlsZUltYWdlVXJsIjoicHJvZmlsZUltYWdlVXJsIiwiZW1haWwiOiI5IiwiZXhwIjoxNjk4OTIyMTYyfQ.UPfEmwp2NL3iD7PnFQ8CcY4EsWd2ajWAbBAaWd1W-4E
Content-Type: application/json

{
  "category": "ART",
  "difficulty": "어려움",
  "title" : "시험기간이 2주 남은 대학생입니다. 이번에는 꼭 장학금을 받고 싶은데 어떻게 해야할까요?",
  "content": "시험공부를 하면서 학점 4.0 이상을 넘어서 장학금을 받고 싶습니다. 학교다니면서 알바까지 하는게 너무 힘듭니다. 받아보신 분들께서 좋은 팁 부탁드립니다."

}

### deleteArticle(질문 삭제)
DELETE http://localhost:8082/api/v1/question/article/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6IuydtO2DnOybhSIsImlkIjoiN2Q4MDE0Y2EtMzQ2NS00OTIxLWEzNGMtM2EzMGJkOGE5NWRjIiwicHJvZmlsZUltYWdlVXJsIjoicHJvZmlsZUltYWdlVXJsIiwiZW1haWwiOiI0IiwiZXhwIjoxNjk4ODk0MTk0fQ.VkTRQ1Ijz1bv3Gt1r3md01yBFfLmFj2BwC8jHS00nxs

### findArticleById(질문 상세조회)
GET http://localhost:8082/api/v1/question/article/3
Accept: application/json

### updateArticleById(질문 업데이트)
PUT http://localhost:8082/api/v1/question/article/3
Content-Type: application/json

{
  "title" : "변경입니다.",
  "content": "바꿔주세요"

}

### insertComment(댓글 등록)
POST http://localhost:8082/api/v1/question/comment/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuaWNrbmFtZSI6Ik5pY2tuYW1lMTIzNCIsImlkIjoiOThlY2ZlYzAtOWM2OS00NjEwLWE2M2YtODAwYzY4MDEwYjdkIiwicHJvZmlsZUltYWdlVXJsIjoicHJvZmlsZUltYWdlVXJsIiwiZW1haWwiOiI5IiwiZXhwIjoxNjk4OTA4MTQ0fQ.yG7C1ANeIBzMRRl60KHbbyKJj09h-NkQ32GEb6TJQTc

{
  "content" : "수정입니다."
}